### ISSUE TITLE
I am getting an error on windows.

### ISSUE THREAD

**Issue by abhidotnet** [zengfu94/MicrosoftRewards#10]
This is the error message. I copied the user agent from the accounts file that you have posted to GitHub.

```
Traceback (most recent call last):
  File "bing.py", line 164, in <module>
    pool.map(search_account, accounts)
  File "C:\Python27\lib\multiprocessing\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
ValueError: Invalid header value 'Mozilla/5.0 (Android 4.4; Mobile; rv:41.0) Gecko/41.0 Firefox/41.0\n'
```

**Comment by zengfu94** [comment]
I don't know how recent you may have updated but yesterday this was fixed by stripping the user agents of the new line carriage.
