### ISSUE TITLE
Doesn't recover from URL open failure

### ISSUE THREAD

**Issue by AnthonyBe** [zengfu94/MicrosoftRewards#16]
I've noticed a few times now that with multiple accounts defined in accounts.txt, if there is a transient error on one search for an account that that account's searches terminates and does not recover, while the remaining accounts do continue.

It would be good if transient errors could be handled more gracefully and searches continue after a number of retries.

Here is the error traceback when I get this sort of problem:

Traceback (most recent call last):
  File "C:\Temp\MicrosoftRewards\MicrosoftRewards-master\bing.py", line 373, in search_account
    gen = gt.queryGenerator(1)
  File "C:\Temp\MicrosoftRewards\MicrosoftRewards-master\googleTrends.py", line 14, in __init__
    self.allQueries = self.__pullAll()
  File "C:\Temp\MicrosoftRewards\MicrosoftRewards-master\googleTrends.py", line 21, in __pullAll
    suggestSet = self.__suggestQueriesSingle(term)
  File "C:\Temp\MicrosoftRewards\MicrosoftRewards-master\googleTrends.py", line 53, in __suggestQueriesSingle
    tree = self.__readXML(URL)
  File "C:\Temp\MicrosoftRewards\MicrosoftRewards-master\googleTrends.py", line 26, in __readXML
    response = urllib2.urlopen(URL)
  File "D:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "D:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "D:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "D:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "D:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

**Comment by zengfu94** [comment]
This should be fixed, lemme know if you still get it.
