### ISSUE TITLE
unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by kkasberg** [zengfu94/MicrosoftRewards#26]
I am getting an error when I try to run the script.

```
MicrosoftRewards$ ./bing.py
Git not found or updates disabled!
Failed to parse:
sleeping for 975 seconds
sleeping for 433 seconds
Traceback (most recent call last):
  File "./bing.py", line 557, in <module>
    pool.map(search_account, accounts)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

```

**Comment by zengfu94** [comment]
You have a blank line or some other issue in your accounts.txt

**Comment by zengfu94** [comment]
The bot should update and show you which account has the error now.
