### ISSUE TITLE
ConnectionError: HTTPSConnectionPool(host='bing.comhttps', port=443): Max retries exceeded

### ISSUE THREAD

**Issue by AnthonyBe** [zengfu94/MicrosoftRewards#43]
Currently using commit d104e47.
I've been noticing that I'm getting an increasing number of these every time the script runs over the last week or two:

```
[14:39:52] accountdeleted@domaindeleted.com: 20/10: desktop search: nepal
[14:39:53] accountdeleted@domaindeleted.com: next search in: 127 seconds
[14:42:02] Traceback (most recent call last):
  File "C:\Temp\MicrosoftRewards\MicrosoftRewards-master\bing.py", line 416, in search_account
    sesh.get(url, verify=False)
  File "D:\Python27\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "D:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='bing.comhttps', port=443): Max retries exceeded with url: //www2.bing.com/search?q=Polish+metal+band+charged+&filters=tnTID:%223B1F3F40-2593-452e-BA57-9573D20ECE59%22+tnVersion:%222165561%22+segment:%22popularnow.carousel%22+tnCol:%221%22+tnOrder:%226c1c2d16-e059-4005-951e-dd9e102a2a4b%22&FORM=HPNN01 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000006BDF2B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

[14:42:02] Caught failed request on: accountdeleted@domaindeleted.com retrying...

```
The script usually continues on fine. Sometimes there will be multiple of these in a row and the script with exit out.

Just wanted to flag this in case it has something to do with the code as opposed to transient internet weirdness.

**Comment by zengfu94** [comment]
I'll look into it. this: host='bing.comhttps' specifically makes me think its adding the https:// when it might already be there.
