### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text' 

### ISSUE THREAD

**Issue by rrosajp** [zengfu94/MicrosoftRewards#48]
[13:40:21] ******@outlook.com: saved cookies for later
[13:40:21] ******@outlook.com: failed to login
[13:40:22] ******@outlook.com: using saved cookies
[13:40:22] ******@outlook.com: current points: 0
[13:40:28] Traceback (most recent call last):
  File "/home/br/bin/bing.py", line 313, in search_account
    if "Join" in soup.find("span",{"class" : "linkText"}).text:
AttributeError: 'NoneType' object has no attribute 'text'

[13:40:28] Caught failed request on: ******@outlook.com retrying...
[13:40:29] ******@outlook.com: using saved cookies
[13:40:29] ******@outlook.com: current points: 0
[13:40:35] Traceback (most recent call last):
  File "/home/br/bin/bing.py", line 313, in search_account
    if "Join" in soup.find("span",{"class" : "linkText"}).text:
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by zengfu94** [comment]
Make sure you're on latest version, it also tells you that it failed to login.

**Comment by rrosajp** [comment]
it's work on win 7 but when i try on pi with same script it not work i'm trying to set cronjob any help would appreciated

**Comment by zengfu94** [comment]
This is a Pi related issue then.

**Comment by rrosajp** [comment]
oh i c thanks
