### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by GeistNet** [zengfu94/MicrosoftRewards#8]
Getting the following error when running the script.  What am i doing wrong??

C:\Users\MicrosoftRewards-master>bing.py
Found accounts.txt
sleeping for 42 seconds
sleeping for 21 seconds
Traceback (most recent call last):
  File "C:\Users\MicrosoftRewards-master\bing.py", line 290, in <module>
    pool.map(search_account, accounts)
  File "C:\Python27\lib\multiprocessing\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
IndexError: list index out of range
C:\Users\MicrosoftRewards-master>

**Comment by zengfu94** [comment]
Can you provide your accounts.txt? Replace emails and passwords with something else

**Comment by rrosajp** [comment]
hey now i have this issue !

Found accounts.txt
sleeping for 386 seconds
Traceback (most recent call last):
  File "D:\GitHub\z_xbmc\zipsss\MicrosoftRewards-master\bing.py", line 304, in <module>
    pool.map(search_account, accounts)
  File "C:\Python27\lib\multiprocessing\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
IndexError: list index out of range

**Comment by zengfu94** [comment]
@rrosajp please git pull and see if you still face it

**Comment by rrosajp** [comment]
i did git pull and run but mow new error

Found accounts.txt
sleeping for 538 seconds
Traceback (most recent call last):
  File "D:\GitHub\z_xbmc\zipsss\MicrosoftRewards-master\bing.py", line 313, in <module>
    pool.map(search_account, accounts)
  File "C:\Python27\lib\multiprocessing\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
NameError: global name 'traceback' is not defined

**Comment by zengfu94** [comment]
@rrosajp that was about 3 commits ago, please pull again.

**Comment by rrosajp** [comment]
now BS not finding form !
i'm posting and testing so don't b mad !
i like to learner this so.

Found accounts.txt
sleeping for 140 seconds
Traceback (most recent call last):
  File "D:\GitHub\z_xbmc\zipsss\MicrosoftRewards-master\bing.py", line 104, in search_account
    form = BS(res.content, "html.parser").findAll("form")[0]
IndexError: list index out of range

**Comment by GeistNet** [comment]
Just updated and now I am getting this error...

Found accounts.txt
sleeping for 48 seconds
Fsailed to parse:
Traceback (most recent call last):
  File "C:\Users\MicrosoftRewards-master\bing.py", line 308, in <module>
    pool.map(search_account, accounts)
  File "C:\Python27\lib\multiprocessing\pool.py", line 251, in map
leeping for 0 seconds
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
Failed to parse:

**Comment by zengfu94** [comment]
@GeistNet Your issue is a blank line or lines in accounts.txt @rrosajp looking into yours

**Comment by GeistNet** [comment]
This is what is in my accounts.txt file...
email@email.com>Password>Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0>Mozilla/5.0 (Android 4.4; Mobile; rv:41.0) Gecko/41.0 Firefox/41.0

**Comment by GeistNet** [comment]
Yep, CR at the end of the file...removed that and we're getting further!  Now receiving this...

Found accounts.txt
ssleeping for 13 seconds
leeping for 59 seconds
email@hotmail.com: logged in
email@hotmail.com: current points: 2249
email@hotmail.com: next search in: 14 seconds
email@hotmail.com: mobile search: ember+days
cwhatley@hotmail.com: next search in: 6 seconds
Traceback (most recent call last):
  File "C:\Users\MicrosoftRewards-master\bing.py", line 197, in search_account
    requests.get("https://bing.com" + offer, cookies=cookies, headers=desktop_headers, verify=False)
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 218, in resolve_redirects
    **adapter_kwargs
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for 'ms-windows-store://collection/?CollectionId=WindowsThemes&OCID=rewards'

email_2@hotmail.com: logged in
email_2@hotmail.com: current points: 29941
email_2@hotmail.com: searches done
email_2@hotmail.com: points earned: 0
email_2@hotmail.com: total points: 29941
Traceback (most recent call last):
  File "C:\Users\MicrosoftRewards-master\bing.py", line 332, in <module>
    os.remove("not_ready.txt")
WindowsError: [Error 2] The system cannot find the file specified: 'not_ready.txt'

**Comment by zengfu94** [comment]
@GeistNet you should be good to go. parse error on rewards is fixed

**Comment by GeistNet** [comment]
Yep, I'm running now!  Thanks!
